// <auto-generated />
using System;
using CategoryService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CategoryService.Infrastructure.Migrations
{
    [DbContext(typeof(CategoryContext))]
    [Migration("20240802050004_AddingCategoryType")]
    partial class AddingCategoryType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoryService.Model.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("45b72a03-15ec-4729-9701-92a0a3b5e036"),
                            CategoryType = "Electronics",
                            Name = "Mobile"
                        },
                        new
                        {
                            Id = new Guid("f7e9da1b-8cbc-49db-be26-459a3029ee14"),
                            CategoryType = "HomeAppliances",
                            Name = "TV"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
